import {
    StyleSheet,
  } from "react-native";

  import {nameCellWidth, nameCellHeight} from './helper.js'; 
  
  
  export const styles = StyleSheet.create({
    
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#b8d2e6',
      paddingBottom: 20, 
    },
    quiz_container: {
        // flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#b8d2e6',
        paddingBottom: 20, 
        },
    name_cell: {
      backgroundColor: '#9fd0f5',
      padding: 0,
      marginVertical: 2,
      marginHorizontal: 2,
      alignItems: 'center',
      width: nameCellWidth,
      height: nameCellHeight,
      borderRadius: 0,
      borderWidth: 1, 
      borderColor: '#0467b3',
    },
    quiz_correct_cell: {
        backgroundColor: '#33cc89',
        padding: 0,
        marginVertical: 2,
        marginHorizontal: 2,
        alignItems: 'center',
        width: nameCellWidth,
        height: nameCellHeight,
        borderRadius: 0,
        borderWidth: 1, 
        borderColor: '#0467b3',
      },
      quiz_wrong_cell: {
        backgroundColor: '#aa3366',
        padding: 0,
        marginVertical: 2,
        marginHorizontal: 2,
        alignItems: 'center',
        width: nameCellWidth,
        height: nameCellHeight,
        borderRadius: 0,
        borderWidth: 1, 
        borderColor: '#0467b3',
      },
    selected_name_cell: {
      backgroundColor: '#60a0ff',
      padding: 0,
      marginVertical: 2,
      marginHorizontal: 2,
      alignItems: 'center',
      width: nameCellWidth,
      height: nameCellHeight,
      borderRadius: 0,
      borderWidth: 1, 
      borderColor: '#0467b3',
    },
    empty_name_cell: {
        backgroundColor: '#b8d2e6',
        padding: 0,
        marginVertical: 2,
        marginHorizontal: 2,
        alignItems: 'center',
        width: nameCellWidth,
        height: nameCellHeight,
        borderRadius: 0,
        borderWidth: 1, 
        borderColor: '#b8d2e6',
      },
    group_name_cell: {
        padding: 0,
        marginBottom: 5,
        marginHorizontal: 0,
        alignItems: 'center',
        width: 99,
        height: 100,
        borderRadius: 0,
        borderWidth: 1, 
    },
    checked_group_cell: {
        backgroundColor: "#bbdd99",
        padding: 0,
        marginVertical: 10,
        marginHorizontal: 10,
        alignItems: 'center',
        width: 100,
        height: 135,
        borderRadius: 0,
        borderWidth: 1, 
    },
    unchecked_group_cell: {
        backgroundColor: "#bbaa99",
        padding: 0,
        marginVertical: 10,
        marginHorizontal: 10,
        alignItems: 'center',
        width: 100,
        height: 135,
        borderRadius: 0,
        borderWidth: 1, 
    },
    main_menu_cell: {
      // backgroundColor: 'green', 
      width: 100, 
      height: 150,  
      alignItems: 'center',
      justifyContent: 'center',
      margin: 10, 
    }
  });